### ISSUE TITLE
question about datasets

### ISSUE THREAD

**Issue by J-zin** [unsuthee/SemanticHashingWeakSupervision#1]
Hi~
i check the datasets you share in google drivers: https://drive.google.com/drive/folders/1OgAXRtHkKPud6IxRiQI55I1kwNAkrtW2
i see they are token sequence in it, like in ng20_train_top101.txt, the data form is:
![image](https://user-images.githubusercontent.com/30493522/66696745-30bdb500-ed01-11e9-85a2-d70fb36debe2.png)
dose it keep the order of the words? or it just the key word in the text?
thanks for your excellent work!

**Comment by unsuthee** [comment]
Hi, sorry for my late reply. The file above (ng20_train_top101.txt) has the following format:
train_doc_id: the 1st nearest doc_id the 2nd nearest doc_id, ... , the k-th nearest doc_id

This is not a token sequence file. 

For this work, the model takes a bag-of-words as input. Hence, it does not keep any word ordering information.

Hope this helps.
